### ISSUE TITLE
Rename `*.ql` files to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [Kacperos155/Mapa-Lini-Kolejowych#3]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all `*.ql` files in this repo to `*.overpassql`  for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment]
@Kacperos155 would a pull request be accepted?

**Comment by Kacperos155** [comment]
Hi,
Sorry you had to wait so long.
I have changed extension to `*.overpassql` in commit 10dbda620ad7098af95d69c6f59b733d3a90fb3f

This is/was a small university project, so I easily forgot to check your issue.

**Comment by FloEdelmann** [comment]
Thanks for renaming!
